print('enter Xa:')
xa = int(input())
print('enter Ya:')
ya = int(input())
print('enter Xb:')
xb = int(input())
print('enter Yb:')
yb = int(input())
ab = ((xb-xa)**2+(yb-ya)**2)**(0.5)
print(f'AB is {ab}')